version: '3.9'

services:
  web:
    container_name: web-app-lmt
    image: webdevops/php-nginx-dev:8.3
    ports:
      - '4602:80'
    volumes:
      - ./www:/app
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
    working_dir: /app
    networks:
      - internal

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: shop
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - internal

volumes:
  mysql_data:

networks:
  internal:
    driver: bridge
